const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const file = path.join(__dirname, '../ui/editor-state.js');
assert.ok(fs.existsSync(file), 'editor-state exposes reversible editing and photo correction commands');
const {History, annotation, addFeature, movePoint, removeFeature, pixelPoint, updateFeature, matchAnnotations} = require(file);
const h = new History({n: 0});
h.commit({n: 1}); h.commit({n: 2});
assert.deepEqual(h.undo(), {n: 1}); assert.deepEqual(h.undo(), {n: 0});
assert.deepEqual(h.redo(), {n: 1}); h.commit({n: 3}); assert.equal(h.canRedo, false);
const current = h.current; current.n = 99; assert.equal(h.current.n, 3);
const a = annotation([100, 80], 'a'.repeat(64));
const b = addFeature(a, 'edge', [[5, 10], [90, 60]]);
assert.equal(a.features.length, 0); assert.equal(b.features.length, 1);
const id = b.features[0].id;
const c = movePoint(b, id, 0, [20, 30]);
assert.deepEqual(c.features[0].points[0], [20, 30]); assert.deepEqual(b.features[0].points[0], [5, 10]);
assert.equal(c.features[0].id, id);
assert.throws(() => movePoint(c, id, 0, [101, 0]), /图像/);
assert.throws(() => addFeature(a, 'face', [[1, 1], [2, 2]]), /至少/);
assert.equal(removeFeature(c, id).features.length, 0);
assert.equal(typeof updateFeature, 'function', 'existing lines can be reclassified and rebound to the current model');
const rebound = updateFeature(c, id, {kind:'uncertain',face_id:'F02',model_fingerprint:'b'.repeat(64)});
assert.equal(rebound.features[0].id, id);
assert.deepEqual(rebound.features[0].points, c.features[0].points);
assert.equal(rebound.features[0].model_fingerprint, 'b'.repeat(64));
assert.throws(()=>updateFeature(c,id,{kind:'face'}), /至少/);
assert.equal(updateFeature(rebound,id,{face_id:''}).features[0].model_fingerprint, undefined);
assert.throws(()=>addFeature(a,'face',[[0,0],[70,60],[0,60],[70,0]]), /自交|退化/);
const face=addFeature(a,'face',[[0,0],[70,0],[70,60],[0,60]]);
assert.throws(()=>movePoint(face,'A1',1,[0,0]), /重复/);
assert.equal(typeof matchAnnotations, 'function');
const repeated=matchAnnotations([a.source_sha256,a.source_sha256],[b,c]);
assert.deepEqual(repeated,[b,c]);
assert.throws(()=>matchAnnotations([a.source_sha256],[b,c]), /重复/);
assert.deepEqual(pixelPoint([60, 50], {s: .5, x: 10, y: 10}, [100, 80]), [100, 80]);
assert.equal(pixelPoint([61, 50], {s: .5, x: 10, y: 10}, [100, 80]), null);
console.log('PASS editor history, branching undo, immutable point edits, original pixels and feature identity');
const canvas=require('../ui/editor-canvas.js');
assert.equal(typeof canvas.rotateFrom,'function','free rotation starts from the currently displayed orientation');
const faceOn=[[0,1,0],[0,0,1],[1,0,0]];
assert.deepEqual(canvas.rotateFrom(faceOn,0,0),faceOn);
const turned=canvas.rotateFrom(faceOn,Math.PI/2,0);
assert.ok(Math.abs(turned[2][1]+1)<1e-12);
