const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const file=path.join(__dirname,'../ui/editor-experience.js');
assert.ok(fs.existsSync(file),'guided experience exposes validated preferences and nonintrusive keyboard actions');
const E=require(file);
assert.equal(E.preferences({}).snap,true);
assert.equal(E.preferences({snap:false}).snap,false);
assert.equal(E.preferences({audience:'invalid',radius:NaN}).audience,'beginner');
assert.equal(E.preferences({radius:999}).radius,12);
assert.equal(E.preferences({audience:'teacher',loupe:true}).audience,'teacher');
assert.equal(E.keyboardAction({key:'Backspace',tagName:'CANVAS',active:true}),'back');
assert.equal(E.keyboardAction({key:'Enter',tagName:'TEXTAREA',active:true}),null);
assert.equal(E.keyboardAction({key:'Escape',tagName:'INPUT',active:true}),null);
assert.equal(E.keyboardAction({key:'Enter',tagName:'CANVAS',active:false}),null);
assert.equal(E.keyboardAction({key:'z',ctrlKey:true,tagName:'CANVAS',active:true}),'undo');
assert.equal(E.drawingHint('face',2,true).canFinish,false);
assert.equal(E.drawingHint('face',3,true).canFinish,true);
assert.equal(E.drawingHint('edge',2,true).canFinish,true);
assert.equal(E.drawingHint('edge',0,false).canFinish,false);
assert.match(E.drawingHint('edit',0,true).text,/拖动/);
assert.equal(E.faceLabels([{id:'F01',modelMiller:null}],[],true).F01,'F01 · 指数未知');
assert.equal(E.faceLabels([{id:'F01',modelMiller:null}],[{id:'F01',index_candidates:{candidates:[{hkl:[1,0,0]}]}}],true).F01,'F01 · 候选(1 0 0)');
console.log('PASS preferences, keyboard scope, guided completion and conditional teaching labels');
const C=require('../ui/editor-canvas.js');
assert.equal(typeof C.labelLayout,'function','teaching labels remain whole and do not cover each other');
const input=[{text:'F02 reference (0 -1 0)',x:80,y:110,width:150,height:20},{text:'F03 reference (0 0 -1)',x:160,y:110,width:150,height:20}];
const placed=C.labelLayout(input,260,200);
assert.equal(placed.length,2);
assert.ok(placed.every(p=>p.left>=0&&p.right<=260&&p.top>=0&&p.bottom<=200));
const [a,b]=placed;
assert.ok(a.right<=b.left||b.right<=a.left||a.bottom<=b.top||b.bottom<=a.top);
assert.deepEqual(input.map(p=>p.y),[110,110]);
assert.equal(typeof E.photoFrame,'function','real-photo object focus keeps original pixel coordinates');
const full=E.photoFrame([960,1280],[402,360]);
const focused=E.photoFrame([960,1280],[402,360],[157,556,709,808]);
assert.ok(focused.s>full.s*2);
const pixel=[370,611],screen=[focused.x+pixel[0]*focused.s,focused.y+pixel[1]*focused.s];
assert.ok(screen[0]>0&&screen[0]<402&&screen[1]>0&&screen[1]<360);
assert.ok(Math.abs((screen[0]-focused.x)/focused.s-pixel[0])<1e-9);
assert.equal(typeof E.saveAction,'function');
assert.equal(E.saveAction('photo',0,2).target,'saveAnnotations');
assert.match(E.saveAction('photo',2,2).reason,/完成/);
assert.match(E.saveAction('photo',0,0).reason,/照片/);
assert.equal(E.saveAction('model',0,0).target,'saveDraft');
