const assert=require('node:assert/strict');
const S=require('../ui/editor-state.js');
assert.equal(typeof S.translateFeature,'function','dragging a line moves the whole annotation atomically');
let a=S.annotation([200,150],'a'.repeat(64));
a=S.addFeature(a,'edge',[[20,20],[100,20]]);
a=S.addFeature(a,'face',[[20,20],[100,20],[100,100],[20,100]]);
const isolated=S.translateFeature(a,'A1',[10,15]);
assert.deepEqual(isolated.features[0].points,[[30,35],[110,35]]);
assert.deepEqual(isolated.features[1].points,a.features[1].points);
const linked=S.translateFeature(a,'A1',[10,15],{linked:true});
assert.deepEqual(linked.features[1].points,[[30,35],[110,35],[100,100],[20,100]]);
assert.deepEqual(a.features[0].points,[[20,20],[100,20]]);
assert.throws(()=>S.translateFeature(a,'A1',[-50,0],{linked:true}),/图像/);
const vertex=S.movePoint(a,'A1',0,[25,30],{linked:true});
assert.deepEqual(vertex.features[1].points[0],[25,30]);
assert.equal(S.hitFeature(a,[22,22],{scale:1,radius:5}).type,'point');
assert.equal(S.hitFeature(a,[60,22],{scale:1,radius:5}).type,'segment');
assert.equal(S.hitFeature(a,[60,22],{scale:1,radius:5}).featureId,'A1','explicit line wins over coincident region border');
assert.equal(S.hitFeature(a,[60,60],{scale:1,radius:5}).type,'region');
assert.equal(S.hitFeature(a,[180,130],{scale:1,radius:5}),null);
const added=S.insertPoint(a,'A1',0,[60,20]);
assert.deepEqual(added.features[0].points,[[20,20],[60,20],[100,20]]);
assert.deepEqual(S.removePoint(added,'A1',1).features[0].points,a.features[0].points);
assert.throws(()=>S.removePoint(a,'A1',0),/至少/);
const replacement=S.replaceFeaturePoints(a,'A1',[[25,25],[90,25]]);
assert.equal(replacement.features[0].id,'A1');
assert.deepEqual(replacement.features[0].points,[[25,25],[90,25]]);
assert.equal(typeof S.translateSegment,'function');
const pushed=S.translateSegment(a,'A2',0,[0,10]);
assert.deepEqual(pushed.features[1].points,[[20,30],[100,30],[100,100],[20,100]]);
assert.throws(()=>S.replaceFeaturePoints(a,'A2',[[0,0],[80,80],[0,80],[80,0]]),/自交|退化/);
assert.equal(typeof S.assertPhotoBinding,'function');
assert.doesNotThrow(()=>S.assertPhotoBinding(a,a.source_sha256,a.image_size));
assert.throws(()=>S.assertPhotoBinding(a,'b'.repeat(64),a.image_size),/照片/);
assert.throws(()=>S.assertPhotoBinding(a,a.source_sha256,[100,100]),/照片/);
console.log('PASS photo corrections: hit testing, whole feature drag, linked points, insert/delete and atomic redraw');
