const escapeHTML=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
'use strict';
const $=id=>document.getElementById(id),dot=(a,b)=>a.reduce((s,x,i)=>s+x*b[i],0),len=v=>Math.hypot(...v),unit=v=>v.map(x=>x/len(v)),mv=(M,v)=>M.map(r=>dot(r,v)),mm=(A,B)=>A.map(r=>B[0].map((_,j)=>r.reduce((s,x,k)=>s+x*B[k][j],0))),cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]],I=[[1,0,0],[0,1,0],[0,0,1]];
const INFO={};
for(const [k,m] of Object.entries(DATA.models))if(m.info)INFO[k]=m.info;
let projectionMode='standard',showRidges=true;
const obliqueMode=()=>['standard','oblique-free'].includes(projectionMode),photoViewMode=()=>['photo','photo-free'].includes(projectionMode);
let groupSelection=[0],showAxes=true;const isSelected=i=>groupSelection.includes(i);
let key=Object.hasOwn(DATA.models,location.hash.slice(1))?location.hash.slice(1):Object.keys(DATA.models)[0],model,selected=0,photoNum=1,view,R=I,zoom=1,wire=false,overlay=false,imageObj=null,photoToken=0,hitPolys=[],bounds,bindings={};
function symbol(s){s=s.trim().replace(/[−–]/g,'-').replace(/(\d)[\u0304\u0305]/g,'-$1');if(/^[({].*[)}]$/.test(s)){if((s[0]==='('&&s.at(-1)!==')')||(s[0]==='{'&&s.at(-1)!=='}'))throw Error('括号不匹配');s=s.slice(1,-1).trim();}let parts=/[ ,]/.test(s)?s.split(/[ ,]+/):s.match(/-?\d/g);if(!parts||parts.length!==(model?.indexing.indexCount||3)||parts.join('')!==s.replace(/[ ,]/g,'')||parts.some(x=>! /^-?\d+$/.test(x)))throw Error('请输入本模型的完整指数：三轴3个、四轴4个整数；多位数用空格分隔。');let a=parts.map(Number);if(a.every(x=>x===0)||a.some(x=>!Number.isSafeInteger(x)||Math.abs(x)>9999))throw Error('不能输入 (000)，指数绝对值需小于 10000。');if(a.length===4&&a[0]+a[1]+a[2]!==0)throw Error('四轴指数必须满足 h+k+i=0，例如 (1 0 -1 0)。');const gcd=(a,b)=>b?gcd(b,a%b):a;let g=a.reduce((r,x)=>gcd(r,Math.abs(x)),0);return a.map(x=>x/g).join(' ');}
const fmt=h=>'('+h.join(' ').replace(/-/g,'−')+')';
const faceLabel=i=>model.faces[i].id+' '+fmt(model.faces[i].modelMiller);
function setup(){model=DATA.models[key];$('query').placeholder=model.indexing.indexCount===4?'F01、(1 0 -1 0) 或 {1 0 -1 0}':'F01、(1 0 0) 或 {1 1 1}';$('miller').placeholder=model.indexing.indexCount===4?'例如 (1 0 -1 0)':'例如 (1 0 -1)';bindings[key]??={};$('title').textContent=`${key} · ${INFO[key].system} · ${INFO[key].title}`;$('description').textContent=INFO[key].desc;$('observations').innerHTML=INFO[key].notes.map((s,i)=>`<div class="obs"><strong>对照 ${i+1}</strong><p>${escapeHTML(s)}</p></div>`).join('')+`<p>${escapeHTML(INFO[key].limits)}</p>`;$('models').querySelectorAll('button').forEach(b=>b.classList.toggle('active',b.dataset.key===key));$('photoSelect').innerHTML=DATA.photos[key].map(p=>`<option value="${p.number}">照片 ${p.number}${DATA.views[key].some(v=>v.photo===p.number)?' · 已设对照视角':' · 原图参考'}</option>`).join('');photoNum=1;selected=(DATA.views[key].find(v=>v.photo===1)||DATA.views[key][0])?.face||0;groupSelection=[selected];$('photoSelect').disabled=!DATA.photos[key].length;renderFacts();$('message').textContent='';loadPhoto();R=model.indexing.standardRotation;setProjection('standard');zoom=1;updateSelection();}
function loadPhoto(){view=DATA.views[key].find(v=>v.photo===photoNum);zoom=1;R=view?view.R:[[.8,0,-.6],[.18,.954,.24],[.5724,-.3,.7632]];if(!view)R=mm([[1,0,0],[0,Math.cos(.3),-Math.sin(.3)],[0,Math.sin(.3),Math.cos(.3)]],[[Math.cos(.6),0,-Math.sin(.6)],[0,1,0],[Math.sin(.6),0,Math.cos(.6)]]);imageObj=null;const token=++photoToken;
if(!DATA.photos[key].length){$('photoSelect').innerHTML='<option>未附照片</option>';$('original').removeAttribute('href');$('original').textContent='可在工作台导入照片并标注';$('overlayMode').disabled=true;$('reset').disabled=true;$('photoHint').textContent='当前输出未附原图';$('metric').textContent='构形来自参考参数。照片配准结果另行保存，不冒充实物验收。';bounds=null;drawModel();drawPhoto();return;}
const p=DATA.photos[key].find(p=>p.number===photoNum);$('original').href=p.path;$('original').textContent='查看完整原图 ↗';$('photoSelect').value=photoNum;$('overlayMode').disabled=!view;$('reset').disabled=!view;$('photoHint').textContent=view?'蓝点：人工角点 · 橙线：所选面 · 绿线：其余可见棱':'本张未配准：仅显示原图，不叠加假定线框';$('metric').textContent=view?`配准面 ${model.faces[view.face].id} · ${view.fitMetric==='boundary'?'面边界均方根偏差':'角点均方根误差'} ${view.rmse.toFixed(1)} px（${view.imageSize?.join(' × ')||'1368 × 1824'} 像素坐标）。${view.silhouette?'已加入外轮廓约束。':'仅单面配准，整体姿态可能有歧义。'}这是拟合误差，不是独立精度验收。`:'这张照片用于补充遮挡处、端面和不同方向的观察。请选择已设对照视角的照片查看叠加。';if(view){const ps=model.vertices.map(v=>project(v,view.R));const xs=ps.map(p=>p[0]),ys=ps.map(p=>p[1]);view.observed.forEach(p=>{xs.push(p[0]);ys.push(p[1])});let x=Math.min(...xs)-65,y=Math.min(...ys)-65;bounds=[x,y,Math.max(...xs)-x+65,Math.max(...ys)-y+65];}else bounds=[0,0,(view?.imageSize?.[0]||imageObj?.naturalWidth||1368),(view?.imageSize?.[1]||imageObj?.naturalHeight||1824)];const img=new Image();img.onload=()=>{if(token!==photoToken)return;imageObj=img;if(!view)bounds=[0,0,img.naturalWidth,img.naturalHeight];drawPhoto();};img.onerror=()=>{if(token===photoToken)$('metric').textContent='原图读取失败：请保持 photos 文件夹与 HTML 的相对位置。'};img.src=p.path;drawModel();drawPhoto();}
function project(v,mat){let q=mv(mat,v);const D=view?view.D:12,s=view?view.scale:180,offset=view?view.offset:[684,912];return [q[0]*s/(1-q[2]/D)+offset[0],-q[1]*s/(1-q[2]/D)+offset[1],q[2]];}
function canvas(id){let c=$(id),w=c.clientWidth,h=c.clientHeight,d=devicePixelRatio||1;c.width=Math.round(w*d);c.height=Math.round(h*d);let ctx=c.getContext('2d');ctx.scale(d,d);return {ctx,w,h};}
function frame(w,h){const b=bounds||[350,500,650,800],s=Math.min(w/b[2],h/b[3]);return {s,x:(w-b[2]*s)/2-b[0]*s,y:(h-b[3]*s)/2-b[1]*s};}
function neighbors(){const out=new Set();model.edges.forEach(e=>{if(e.faces.some(isSelected))e.faces.forEach(i=>{if(!isSelected(i))out.add(i)})});return out;}
function drawMesh(ctx,mat,toScreen,asLines=false){const adj=neighbors(),oblique=!asLines&&obliqueMode(),perspective=asLines||photoViewMode();let visible=model.faces.map((f,i)=>{let c=mv(mat,f.center),n=mv(mat,f.n),ray=oblique?[.45,.30,1]:perspective?[-c[0],-c[1],(view?.D||12)-c[2]]:[0,0,1];return {f,i,z:dot(c,unit(ray)),front:dot(n,ray)>1e-8,shade:dot(n,unit(ray))};}).sort((a,b)=>a.z-b.z);if(wire&&!asLines){ctx.setLineDash([3,4]);ctx.strokeStyle='#71837965';for(let e of model.edges){let a=toScreen(model.vertices[e.ids[0]]),b=toScreen(model.vertices[e.ids[1]]);ctx.beginPath();ctx.moveTo(...a);ctx.lineTo(...b);ctx.stroke()}ctx.setLineDash([])}for(let {f,i,front,shade} of visible){if(!front)continue;let ps=f.ids.map(j=>toScreen(model.vertices[j]));ctx.beginPath();ps.forEach((p,j)=>j?ctx.lineTo(...p):ctx.moveTo(...p));ctx.closePath();if(!asLines){let base=['333','722','7518','3519'].includes(key)?43:100;ctx.fillStyle=isSelected(i)?'#dda76a':adj.has(i)?'#a5bca2':`hsl(${base} ${base===43?30:7}% ${48+20*shade}%)`;ctx.fill();ctx.strokeStyle='#314b43';ctx.lineWidth=1.1;ctx.stroke();hitPolys.push({i,ps});let p=toScreen(f.center),area=Math.abs(ps.reduce((s,p,j)=>s+p[0]*ps[(j+1)%ps.length][1]-p[1]*ps[(j+1)%ps.length][0],0))/2;ctx.font='bold 11px system-ui';ctx.textAlign='center';ctx.fillStyle='#152b24';ctx.fillText(area>1400?faceLabel(i):f.id,p[0],p[1]+3);}else{ctx.lineWidth=isSelected(i)?2.8:1.6;ctx.strokeStyle=isSelected(i)?'#ff9326':'#16ecd7';ctx.stroke();let p=toScreen(f.center);ctx.font='bold 11px system-ui';ctx.textAlign='center';ctx.lineWidth=3;ctx.strokeStyle='#14342b';ctx.strokeText(f.id,p[0],p[1]);ctx.fillStyle=isSelected(i)?'#ffd597':'#e4fffa';ctx.fillText(f.id,p[0],p[1]);}}
if(showRidges&&model.splitRidges){const front=new Set(visible.filter(x=>x.front).map(x=>x.i));ctx.strokeStyle=asLines?'#ff68ed':'#923cb1';ctx.lineWidth=asLines?3.5:2.6;for(let e of model.splitRidges){if(!e.faces.some(i=>front.has(i)))continue;let a=toScreen(model.vertices[e.ids[0]]),b=toScreen(model.vertices[e.ids[1]]);ctx.beginPath();ctx.moveTo(...a);ctx.lineTo(...b);ctx.stroke();}}}
// Keep the initial textbook framing fixed: rotation changes pose, never fit-to-window scale.
function crystalAxes(){return model.indexing.displayAxes||[0,1,2].map(i=>model.indexing.basis.map(r=>r[i]));}
function modelFrame(w,h){const rad=Math.max(...model.vertices.map(len)),extra=[];for(const axis of crystalAxes())for(let sign of [-1,1])extra.push(unit(axis).map(x=>x*rad*1.08*sign));const pp=[...model.vertices,...extra].map(v=>{const p=mv(model.indexing.standardRotation,v);return [p[0]-.45*p[2],-p[1]+.30*p[2]];}),xs=pp.map(p=>p[0]),ys=pp.map(p=>p[1]),loX=Math.min(...xs),hiX=Math.max(...xs),loY=Math.min(...ys),hiY=Math.max(...ys);return {scale:Math.min((w-75)/(hiX-loX),(h-95)/(hiY-loY)),cx:(loX+hiX)/2,cy:(loY+hiY)/2};}
function drawModel(){if(!model)return;const {ctx,w,h}=canvas('modelCanvas');ctx.fillStyle='#e8ece5';ctx.fillRect(0,0,w,h);hitPolys=[];let trans;if(view&&photoViewMode()){let t=frame(w,h),cx=w/2,cy=h/2;trans=v=>{let p=project(v,R);return [cx+(p[0]*t.s+t.x-cx)*zoom,cy+(p[1]*t.s+t.y-cy)*zoom]};}else{let project2=v=>{let p=mv(R,v);return obliqueMode()?[p[0]-.45*p[2],-p[1]+.30*p[2]]:[p[0],-p[1]];},framing=modelFrame(w,h),scale=framing.scale*zoom,cx=framing.cx,cy=framing.cy;trans=v=>{let p=project2(v);return [w/2+(p[0]-cx)*scale,h/2+(p[1]-cy)*scale]};}
drawMesh(ctx,R,trans);if(showAxes)drawAxes(ctx,R,trans,w,h);ctx.textAlign='left';ctx.font='12px system-ui';ctx.fillStyle='#5e746b';ctx.fillText(`${key} / ${INFO[key].system} / ${model.faces.length} 面 · ${projectionMode==='standard'?'教材定向（斜投影）':photoViewMode()?'照片视角（透视）':'自由旋转'}`,15,23);}
function drawPhoto(){const {ctx,w,h}=canvas('photoCanvas');ctx.fillStyle='#dde7e1';ctx.fillRect(0,0,w,h);if(!DATA.photos[key].length){ctx.textAlign='center';ctx.fillStyle='#284f47';ctx.font='bold 20px system-ui';ctx.fillText('参考模型 · 当前未附照片',w/2,100);ctx.font='14px system-ui';ctx.fillText('返回工作台可导入原图与角点标注',w/2,140);return;}if(!imageObj){ctx.fillStyle='#537568';ctx.font='13px system-ui';ctx.fillText('读取本地原图…',20,35);return;}let t=frame(w,h);ctx.save();ctx.translate(t.x,t.y);ctx.scale(t.s,t.s);ctx.drawImage(imageObj,0,0,(view?.imageSize?.[0]||imageObj?.naturalWidth||1368),(view?.imageSize?.[1]||imageObj?.naturalHeight||1824));ctx.restore();if(overlay&&view){const transform=v=>{let p=project(v,view.R);return [p[0]*t.s+t.x,p[1]*t.s+t.y]};drawMesh(ctx,view.R,transform,true);view.observed.forEach(p=>{ctx.beginPath();ctx.arc(p[0]*t.s+t.x,p[1]*t.s+t.y,4,0,Math.PI*2);ctx.fillStyle='#357bff';ctx.fill();ctx.lineWidth=1;ctx.strokeStyle='white';ctx.stroke()});}}
function updateSelection(){let f=model.faces[selected],adj=[...neighbors()];$('selected').innerHTML=`<div class="faceid">${f.id} ${fmt(f.modelMiller)}</div><div>${groupSelection.length>1?'已选整个晶形 '+groupSelection.length+' 面；以下数值对应本组首面。':''}</div><strong>${escapeHTML(f.label)}</strong><div>${f.ids.length} 条边 · ${adj.length} 个共棱邻面</div><div>邻面：${adj.map(i=>model.faces[i].id).join('、')}</div><div>模型外法线（原几何X,Y,Z）：<br>${f.n.map(x=>x.toFixed(3)).join(' / ')}</div><div id="assigned"></div><p>${escapeHTML(f.indexStatus)}。本页采用右手参考晶轴。</p>`;$('assigned').textContent=bindings[key][selected]?'晶面符号（用户标定）：('+bindings[key][selected]+')':'模型指数：'+fmt(f.modelMiller)+' · 已反算核对法线';$('miller').value=bindings[key][selected]||'';$('facebuttons').innerHTML=model.faces.map((f,i)=>`<button data-i="${i}" class="${isSelected(i)?'active':''}">${f.id} ${fmt(f.modelMiller)}</button>`).join('');$('facebuttons').querySelectorAll('button').forEach(b=>b.onclick=()=>selectFace(+b.dataset.i,true));$('topology').textContent=`当前构形：V=${model.vertices.length}，E=${model.edges.length}，F=${model.faces.length}；V−E+F=2。已检查每条棱由两个面共用。`;graph();drawModel();drawPhoto();}
function selectFace(i,orient,group){selected=i;groupSelection=group||[i];if(orient){if(view&&photoViewMode()){const cv=$('modelCanvas');zoom*=frame(cv.clientWidth,cv.clientHeight).s*view.scale/modelFrame(cv.clientWidth,cv.clientHeight).scale;}setProjection('free');let n=model.faces[i].n,up=Math.abs(n[1])>.9?[0,0,-1]:[0,1,0],right=unit(cross(up,n));R=[right,cross(n,right),n];}updateSelection();}
function graph(){let N=model.faces.length,adj=neighbors();let p=model.faces.map((f,i)=>[170+133*Math.cos(2*Math.PI*i/N-Math.PI/2),155+133*Math.sin(2*Math.PI*i/N-Math.PI/2)]);$('graph').innerHTML=`<svg viewBox="0 0 340 310" width="100%" height="100%">${model.edges.map(e=>{let [i,j]=e.faces;return `<line x1="${p[i][0]}" y1="${p[i][1]}" x2="${p[j][0]}" y2="${p[j][1]}" stroke="${isSelected(i)||isSelected(j)?'#b57b46':'#d3dbcd'}" stroke-width="${isSelected(i)||isSelected(j)?2:1}"/>`}).join('')}${model.faces.map((f,i)=>`<g data-i="${i}" role="button" tabindex="0" aria-label="定位 ${f.id}" style="cursor:pointer"><circle cx="${p[i][0]}" cy="${p[i][1]}" r="14" fill="${isSelected(i)?'#d9a66c':adj.has(i)?'#9db295':'#e9ede3'}" stroke="#778d79"/><text x="${p[i][0]}" y="${p[i][1]+3.5}" text-anchor="middle" fill="#254439" font-size="9">${f.id}</text></g>`).join('')}</svg>`;$('graph').querySelectorAll('g').forEach(g=>{g.onclick=()=>selectFace(+g.dataset.i,true);g.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();selectFace(+g.dataset.i,true)}}});}
function renderFacts(){let x=model.indexing;const forms=x.forms.map(g=>'{'+g.representative.join(' ')+'} × '+g.faces.length).join('；');$('crystalFacts').innerHTML=`<table><tr><th>对称型</th><td>${escapeHTML(x.symmetry)} / ${escapeHTML(x.pointGroup)} <span class="tag">${escapeHTML(x.status)}</span></td></tr><tr><th>晶系</th><td>${escapeHTML(model.crystalSystem)}${model.mineralName?' · '+escapeHTML(model.mineralName):''}</td></tr><tr><th>结晶轴的选择</th><td>${escapeHTML(x.axisChoice)}<br>${escapeHTML(x.axisConvention)}<br><strong>${escapeHTML(x.standardPlacement)}</strong></td></tr><tr><th>几何常数特征</th><td>${escapeHTML(x.geometricFeatures)}</td></tr><tr><th>晶面符号</th><td>${forms}<br>模型参考指数；下方列出每个面的符号。</td></tr></table>`;$('indexBasis').textContent=x.basisNote+(x.literatureCell?' '+x.literatureCell:'');$('formbuttons').innerHTML=x.forms.map((g,i)=>`<button data-form="${i}">{${g.representative.join(' ')}} · ${g.faces.length} 面</button>`).join('');$('formbuttons').querySelectorAll('button').forEach(b=>b.onclick=()=>{let g=x.forms[+b.dataset.form];selectFace(g.faces[0],true,g.faces)});$('faceTable').innerHTML='<table class="index-table"><tr><th>面</th><th>晶面符号</th><th>形态位置 / 编号依据</th><th>验证</th></tr>'+model.faces.map((f,i)=>`<tr><td><button data-face="${i}">${f.id}</button></td><td>${fmt(f.modelMiller)}</td><td>${escapeHTML(f.label)}${f.photoEvidence?'<br><small>'+escapeHTML(f.photoEvidence)+'</small>':''}</td><td>法线反算一致 · ${escapeHTML(f.indexStatus)}</td></tr>`).join('')+'</table>';$('faceTable').querySelectorAll('button').forEach(b=>b.onclick=()=>selectFace(+b.dataset.face,true));}
function drawAxes(ctx,mat,projector,w,h){let A=crystalAxes(),labels=model.indexing.axisLabels||['a','b','c'],rad=Math.max(...model.vertices.map(len)),o=projector([0,0,0]);for(let i=0;i<A.length;i++)for(let sign of [-1,1]){let v=unit(A[i]).map(x=>x*rad*1.08*sign),p=projector(v),color=(A.length===4?['#b23f35','#26785b','#986333','#315faf']:['#b23f35','#26785b','#315faf'])[i];ctx.globalAlpha=sign>0?1:.48;ctx.setLineDash(sign>0?[4,4]:[2,5]);ctx.strokeStyle=color;ctx.lineWidth=1.4;ctx.beginPath();ctx.moveTo(...o);ctx.lineTo(...p);ctx.stroke();ctx.setLineDash([]);let a=Math.atan2(p[1]-o[1],p[0]-o[0]);if(sign>0){ctx.beginPath();ctx.moveTo(...p);ctx.lineTo(p[0]-7*Math.cos(a-.45),p[1]-7*Math.sin(a-.45));ctx.moveTo(...p);ctx.lineTo(p[0]-7*Math.cos(a+.45),p[1]-7*Math.sin(a+.45));ctx.stroke();}ctx.font='bold 13px system-ui';ctx.textAlign='center';let lx=Math.min(w-20,Math.max(20,p[0]+10)),ly=Math.min(h-25,Math.max(36,p[1]-7));ctx.fillStyle='#fffef9';ctx.fillRect(lx-13,ly-14,26,19);ctx.fillStyle=color;ctx.fillText((sign>0?'+':'−')+labels[i],lx,ly);}ctx.globalAlpha=1;ctx.fillStyle='#152e29';ctx.font='bold 12px system-ui';ctx.fillText('O',o[0]+7,o[1]+14);}
function setProjection(mode){projectionMode=mode;$('standard').classList.toggle('active',mode==='standard');$('reset').classList.toggle('active',mode==='photo');$('modelHint').textContent=mode==='standard'?(model.indexing.indexCount===4?'四轴定向 · a₁/a₂/a₃ 基面内120°，c直立 · 晶轴随模型转动':'按表4.1安置 · a前后、b左右、c直立 · 拖动后可用“教材定向”复位'):photoViewMode()?'照片视角：晶轴随模型姿态转动 · 教材安置请点“教材定向”':'自由旋转 · 晶轴随晶体转动 · 点击教材定向复位';$('ridges').hidden=!model.splitRidges?.length;}
$('models').innerHTML=Object.keys(INFO).map(k=>`<button data-key="${k}">${k} · ${INFO[k].system}</button>`).join('');$('models').querySelectorAll('button').forEach(b=>b.onclick=()=>{key=b.dataset.key;history.replaceState(null,'','#'+key);setup()});
$('photoSelect').onchange=e=>{photoNum=+e.target.value;loadPhoto();setProjection(view?'photo':'free');if(view)selectFace(view.face,false);else drawModel();};$('reset').onclick=()=>{R=view.R;setProjection('photo');zoom=1;drawModel()};$('iso').onclick=()=>{setProjection('free');let a=.6,b=.3;R=mm([[1,0,0],[0,Math.cos(b),-Math.sin(b)],[0,Math.sin(b),Math.cos(b)]],[[Math.cos(a),0,-Math.sin(a)],[0,1,0],[Math.sin(a),0,Math.cos(a)]]);zoom=1;drawModel()};$('wire').onclick=()=>{wire=!wire;$('wire').classList.toggle('active',wire);drawModel()};$('photoMode').onclick=()=>{overlay=false;$('photoMode').classList.add('active');$('overlayMode').classList.remove('active');drawPhoto()};$('overlayMode').onclick=()=>{overlay=true;$('overlayMode').classList.add('active');$('photoMode').classList.remove('active');drawPhoto()};
$('find').onclick=()=>{try{let q=$('query').value.trim().toUpperCase(),ids=[];if(/^F\d+$/.test(q)){ids=model.faces.flatMap((f,i)=>+f.id.slice(1)===+q.slice(1)?[i]:[]);}else{let normalized=symbol(q);if(q.startsWith('{')){ids=model.faces.flatMap((f,i)=>f.formOrbit.some(h=>h.join(' ')===normalized)?[i]:[]);}else ids=model.faces.flatMap((f,i)=>f.modelMiller.join(' ')===normalized||bindings[key][i]===normalized?[i]:[]);}if(!ids.length)throw Error('当前参考基底与模型中不存在这个面或晶形；不会用相近面替代。');$('message').textContent=ids.length>1?'按 '+model.indexing.pointGroup+' 展开，选中 '+ids.length+' 个等价面。':'';selectFace(ids[0],true,ids);}catch(e){$('message').textContent=e.message;}};$('query').onkeydown=e=>{if(e.key==='Enter')$('find').click()};
$('bind').onclick=()=>{try{let s=symbol($('miller').value);if(Object.entries(bindings[key]).some(([i,t])=>+i!==selected&&s===t))throw Error('该符号已分配给另一面，请先核对。');bindings[key][selected]=s;$('message').textContent='已添加用户标定，仅保留在本次页面会话。';updateSelection();}catch(e){$('message').textContent=e.message;}};$('opposite').onclick=()=>{let n=model.faces[selected].n,i=model.faces.findIndex(f=>dot(n,f.n)<-1+1e-6);if(i<0){$('message').textContent='此面在当前模型中没有平行的相反面。';return;}$('message').textContent='';selectFace(i,true)};
$('standard').onclick=()=>{R=model.indexing.standardRotation;setProjection('standard');zoom=1;drawModel()};$('ridges').onclick=()=>{showRidges=!showRidges;$('ridges').classList.toggle('active',showRidges);drawModel();drawPhoto()};
$('axes').onclick=()=>{showAxes=!showAxes;$('axes').classList.toggle('active',showAxes);drawModel()};
let drag=null,moved=0;$('modelCanvas').onpointerdown=e=>{drag=[e.clientX,e.clientY];moved=0;$('modelCanvas').setPointerCapture(e.pointerId)};$('modelCanvas').onpointermove=e=>{if(!drag)return;if(projectionMode==='standard')setProjection('oblique-free');else if(projectionMode==='photo')setProjection('photo-free');let x=(e.clientX-drag[0])*.008,y=(e.clientY-drag[1])*.008;moved+=Math.abs(x)+Math.abs(y);R=mm([[1,0,0],[0,Math.cos(y),-Math.sin(y)],[0,Math.sin(y),Math.cos(y)]],mm([[Math.cos(x),0,Math.sin(x)],[0,1,0],[-Math.sin(x),0,Math.cos(x)]],R));drag=[e.clientX,e.clientY];drawModel()};$('modelCanvas').onpointerup=e=>{drag=null;if(moved>.035)return;let b=$('modelCanvas').getBoundingClientRect(),x=e.clientX-b.left,y=e.clientY-b.top;for(let {i,ps} of [...hitPolys].reverse()){let inside=false;for(let j=0,k=ps.length-1;j<ps.length;k=j++){let a=ps[j],b=ps[k];if((a[1]>y)!=(b[1]>y)&&x<(b[0]-a[0])*(y-a[1])/(b[1]-a[1])+a[0])inside=!inside;}if(inside){selectFace(i,false);break}}};$('modelCanvas').onpointercancel=()=>drag=null;$('modelCanvas').addEventListener('wheel',e=>{e.preventDefault();zoom=Math.min(2.5,Math.max(.45,zoom*Math.exp(-e.deltaY*.001)));drawModel()},{passive:false});new ResizeObserver(()=>{drawModel();drawPhoto()}).observe($('modelCanvas').parentElement);new ResizeObserver(drawPhoto).observe($('photoCanvas').parentElement);setup();
